### ISSUE TITLE
Application theme is always light when application starts.

### ISSUE THREAD

**Issue by aannenko** [Windows-XAML/Template10#1014]
Application theme is always light when application starts. This is true even when you switch to dark theme in the app's settings and restart the app.
To fix this, simply remove the `RequestedTheme="Light"` property setter from the App.xaml file.

**Comment by calloncampbell** [comment]
I believe the reason it's defaulted to white is because that is the new standard for Microsoft's UWP apps.

**Comment by dg2k** [comment]
Don't think white is the preferred theme although apps tend to choose more white than dark.
The three themes, namely Default (aka Dark) Theme, Light Theme and HighContrast Theme are the available standards. There is no suggestion of a preferred standard. It's down to the developer and the user.

The developer may provide options for the user to choose a preferred theme through settings; in some cases the developer may for whatever reason restrict the options. If on the other hand the app is aimed at where user accessibility is paramount (say, for visually impaired) then the implementation of HighContrast Theme may be a requirement.

To come back to the `RequestedTheme="Light"` in the App.xaml file -- that is not a suggestion for favoring the Light Theme. You just got to pick one to start off, it could have been equally `RequestedTheme="Default"` and nothing is implied by that.

In the final implementation,
- the theme is set in the App ctor(). The theme value normally comes from settings that the user persisted through options setting.
- the developer conveniently defines theme options via a style file (Custom.xaml used for sample projects). The style definitions can be applied to various controls as Static Resources and this can be as comprehensive as one wishes - not only for HamburgerMenu and PageHeader, but for theme styling specific to the app.
- you can even change the themes and colors at runtime ... where do you want to stop ? It all depends ...

**Comment by aannenko** [comment]
Cool! But this time it is just a small defect. The theme is initialized twice: once in the App.xaml.cs ctor and the second time - in the Custom.xaml
If the Custom.xaml does not contain a theme setter and settings storage doesn't have a key for a current theme, the SettingsService instance's AppTheme property returns light theme which is just enough for not having a theme setter in the Custom.xaml

**Comment by JerryNixon** [comment]
Worth pointing out that Dark is the internally preferred theme only on phone, Light is the preferred theme on desktop applications. You can confirm this with the first-party apps shipping with Windows 10. Or, you can just trust me. This, by the way, was a decision that was made recently. In the recent past, Dark was the default theme for all apps. I've noticed that many of the bigger first party apps, like News, still seem to prefer Light even on mobile.

**Comment by jp-weber** [comment]
I agree with you. But what is with Redstone? In Redstone, the system theme can be change to black, so the app should use at start the right default value(in this case black). 

At my app, I implemented two other variable, one for a checkbox of the toggleswitch of the theme, to say "I want change the theme" and the other for the default windows theme(to disable the checkbox for the TS and set the right theme back).

**Comment by JerryNixon** [comment]
Should it?

**Comment by jp-weber** [comment]
Why not? ;)
It would be more logical in Redstone, but it can basically be implemented by any programmer yourself. 
In the end, we need only update the setting sample.

It is just a suggestion and no real problem :)

**Comment by JerryNixon** [comment]
Not sure what to do here.

**Comment by JerryNixon** [comment]
Okay, I think you are right. Since the settings in Minimal and Hamburger templates both default to light, this only really impacts Blank. I added an explicit set to Light in the constructor of the App.xaml. I am still not sure any of this is the best thing to do, but it's where we are now.

**Comment by aannenko** [comment]
Hey! Do you hear me?

In the App.xaml.cs ctor there is a `RequestedTheme = _settings.AppTheme;` string of code which sets the app's theme each and every time during the app's initialization. If the theme is not saved in the app's settings storage, the `_settings.AppTheme` will return Light theme, otherwise - the theme that was read from the app's settings storage.

There is no reason to set the theme explicitly anywhere during the application initialization! SettingsService does everything for you. The only modification we can benefit from is to make the `_settings.AppTheme` return the current system theme instead of just Light when the theme is not saved in the app's settings storage.
