### ISSUE TITLE
Update NavViewEx

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1698]
There are several things wrong with it, yet it is close.

- [ ] Get it to build, there are some things
- [ ] Update it to use Nuget T10 packages
- [ ] Update the sample app.
- [ ] Update the `.nuspec` file
- [ ] Upload to Nuget.org for `Windows-XAML`

**Comment by jp-weber** [comment]
I want work on point 1-3, because I have already implemented this in large parts of my fork. For me, it makes sense, if we use WinUI library for the NavigationView.

https://github.com/jp-weber/Template10/tree/master/Source/Template10.Extras.16299/Controls

In the sample project I am looking for better ways to set the header in a simple way. We could add all header templates to the shellpage resource list and set them as HeaderTemplates after navigation or loading. With a naming convention you could set here e.g. '**X**HeaderTemplate'. 

For the individual pages, e.g MainPage.xaml.cs you could now add the ViewModel of the page as (ShellPage).Header content, so that commands from the ViewModel can be added to the template.

**Comment by JerryNixon** [comment]
One thing to consider is that I would like to break this out to its own Nuget package. I also think it might make sense to consider how (if) we can decouple it from Template10 so it would be useful outside of using the framework. Still not sure. Also, I only care about Template10 2 support.
