### ISSUE TITLE
Application get stuck in slash screen after prelaunch

### ISSUE THREAD

**Issue by pekspro** [Windows-XAML/Template10#612]
After prelaunch the samples applications get stuck in slash screen (and my real life application too). I’ve already describe this and some relates issues in #595 but it looks it get unnoticed :-(.

**Comment by JerryNixon** [comment]
Could you post a simple snippet of code of what you are doing?

**Comment by pekspro** [comment]
I’m using the Tiles (and Toast)" without any changes. Replicate the issue like this:

• Launch this sample with Debug -> Other debug targets -> Debug Universal Windows App Launch.
• In Lifecycle Events select Suspend.
• Wait at least 10 seconds.
• In Lifecycle Event select Resume.
• Application is now stuck in splash screen.

**Comment by JerryNixon** [comment]
I cannot replicate this. Also, Prelaunch can (at this time) only be invoked by WACK. How are you concluding that this is a Prelaunch issue?

**Comment by pekspro** [comment]
No, you could use Visual Studio 2015 to launch the application in prelaunch mode. Again, use the menu Debug -> Other debug targets -> Debug Universal Windows App Launch.

Here is an article about it:
https://blogs.msdn.microsoft.com/visualstudioalm/2015/11/30/debug-uwp-prelaunch-with-vs2015/

You also need to suspend and resume the app with the instruction I wrote above to see the problem.

**Comment by JerryNixon** [comment]
This is now resolved.

**Comment by ktd12** [comment]
Hi Jerry.  I have the same problem as pekspro.    I am using Template 10 source that I pulled down this morning (I needed the fix for #488) and I just added your prelaunch (#612) change.  The good news is that the problem no longer happens in Visual Studio when testing prelaunch (Debug App Prelaunch > Suspend > Resume).  Nice work!  However, my app is still failing the WACK prelaunch test.   I would love to know exactly what that prelaunch WACK Test does.

**Comment by JerryNixon** [comment]
Me, too, Karen. Driving me up the wall! I need to ping the Wack team and get them to walk me through what it is exactly doing.

**Comment by ktd12** [comment]
You rock!  Thanks.  I learned about the bootstrapper code in the process, but you figured it out the solution before I did.  FYI, I did figure out that overriding OnPrelaunchAsync in my App.xaml.cs and setting "continueStartup = false" would get the Visual Studio test to work (the splash screen would not be stuck).  I mention this in case it's helpful.  On the positive side, my app (Visual Timers) has been using template 10 since September and has been in the store for awhile. FYI - If it wasn't for Template 10, I would have given up developing apps after this last reincarnation of the platform (I have been here since Windows phone 7). The Visual Studio built-in project templates for uwp are not what they need to be.  Thank you sooooo much for creating Template 10.

**Comment by pekspro** [comment]
I can also confirm that this now seems to be solved :-). I’m tested my application in debug mode and through WACK and everything seems to be fine! I’m even override OnPrelaunchAsync and set runOnStartSync to true and everything was still fine. I’m very grateful for this.

**Comment by ktd12** [comment]
More good news.  I figured out why my app was failing the WACK prelaunch test.  See issue #668.  I am also now taking advantage of Prelaunch by overriding OnPrelaunchAsync and it works very nicely (it really improved app startup time because I load all of my data in Prelaunch).
