### ISSUE TITLE
XAML parser error

### ISSUE THREAD

**Issue by youtoofan** [Windows-XAML/Template10#65]
I've referenced the Template10 project via nuget.
My shell.xaml is the same as the minimal project sample.

When I run my app, I get this error:

WinRT information: Cannot locate resource from 'ms-appx:///Template10Library/Controls/HamburgerMenu.xaml'. [Line: 19 Position: 52]

Do I need to create this resource myself in my project ?

**Comment by CHMaagaard** [comment]
I've also referenced via Nuget and my shell is also as in the minimal project sample. 

I get this error:
WinRT information: Cannot deserialize XBF metadata type list as 'HamburgerMenu' was not found in namespace 'Template10.Controls'. [Line: 0 Position: 0]

If I reference the Template10 project via the visual studio project directly everything works fine. I guess the Nuget package has to be recompiled/updated.

**Comment by JerryNixon** [comment]
This is so strange. I have been talking to the Nuget team about this. There's no good explanation for this. Please keep testing and let me know if you se a pattern that you see that might be the cause. I have updated the current nuget package and it should resolve this (this time).

**Comment by youtoofan** [comment]
Jerry, this still isn't fixed.
I upgraded the Template10 nuget package to the latest version: 1.0.2.2-preview.

When I navigate to the bin folder and right click on the template10.dll to look at the details it still shows version 1.0.0.0

**Comment by JerryNixon** [comment]
Yep. I am experiencing it, too.

**Comment by callummoffat** [comment]
I'm getting this error as well. Very annoying; what is causing it? Has anyone figured it out?

**Comment by JerryNixon** [comment]
I have figured out the problem! I will be updating NuGet today.

**Comment by youtoofan** [comment]
Awesome, I'll keep an eye on the updated package!

**Comment by callummoffat** [comment]
Where is the new Nuget package? I've been waiting a while for it to show up.

**Comment by zangai** [comment]
Did you manage to update NuGet?

**Comment by JerryNixon** [comment]
Adding the xbf file to the NuGet pack has resolved this issue for the PageHeader control. However, this error for the HamburgerButton remains. Still working.

**Comment by callummoffat** [comment]
Any way I can help out with this pesky error?

**Comment by JerryNixon** [comment]
Try version 1.0.4 now in NuGet

**Comment by youtoofan** [comment]
I can confirm the new NuGet package does the trick. Thanks!

**Comment by keneniah** [comment]
I get the same error in version 1.0.8. What's really strange is that this error didn't popup at the beginning (it worked for a couple of days) but occurred suddenly. Is there any newer version than 1.0.8 available?

**Comment by callummoffat** [comment]
No, there isn't. If you want the latest version of Template 10, you'll need
to download it from Github and link it to your project directly.

_Callum Moffat_
App Developer
Windows 10 Enthusiast

---

Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by keneniah** [comment]
OK, thank you, downloading is easy but could you briefly explain, how I link it to my project? Then I could check if the error has gone in the latest version.

**Comment by MichaelPetrinolis** [comment]
Create a directory c:\nuget-local and add a NuGet source pointing to that directory. Close all vs instances, open template 10 and rebuild release anycpu. Add a reference to template10, using nuget-local source. If you sync from upstream, in order to refresh to latest version you must close the vs instances that reference it.

**Comment by keneniah** [comment]
Thank you very much, I figured it out and it works ;-)

**Comment by realworld666** [comment]
Is this issue back in 1.1.0? 
Cannot deserialize XBF metadata type list as 'HamburgerMenu' was not found in namespace 'Template10.Controls'. [Line: 0 Position: 0]

**Comment by callummoffat** [comment]
I'll look into this. It's a definite possibility; I haven't experienced it in my app for a little while, but during some experimentation with the November Update SDK (prior to the release of 1.1.0), I did run into it.

**Comment by gregstoll** [comment]
I'm also hitting this for the first time after upgrading one of my apps to 1.1.0 (via the NuGet)

**Comment by IAmWaseem** [comment]
Changing your current platform from x86 to x64 and vise versa solves the problem. Its just a XAML editor bug. @JerryNixon
